version: 1.0.{build}
configuration: Release

environment:
  COVERALLS_REPO_TOKEN:
    secure: u6gVv4SNWKtYVaoBf/YE6iTQdYqxMXd3vXFlJ+feZikfTcpubLXulqz3DPQYMzeP

before_build:
- nuget install redis-64 -excludeversion
- redis-64\redis-server.exe --service-install
- redis-64\redis-server.exe --service-start
- nuget restore Remember.sln

build:
  project: Remember.sln
  verbosity: minimal

after_test:
- packages\OpenCover.4.5.3723\OpenCover.Console.exe -register:user -target:"xunit.console.clr4.x86.exe" -targetargs:"Remember.Tests.dll" -output:coverage.xml "-filter:+[Remember]* -[Remember.Tests]*" -targetdir:"Remember.Tests\bin\Release"
- packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover coverage.xml
